### ISSUE TITLE
索敌时出现匹配状态失败

### ISSUE THREAD

**Issue by Winger-Wang** [OpenWSGR/AutoWSGR#108]
使用脚本在索敌失败的时候会出现匹配状态失败，具体表现为卡在索敌界面直到失败后才跳至阵型选择界面。

手动操作时没问题，使用脚本能够稳定复现。

```
Traceback (most recent call last):
  File "C:\Users\winger\Documents\WSGR\decisive_battle.py", line 28, in <module>
    decisive_battle.run_for_times(2)  # 数字为决战出击的次数
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\decisive_battle.py", line 195, in run_for_times
    self.start_fight()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\decisive_battle.py", line 728, in start_fight
    res = self.fight()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\decisive_battle.py", line 721, in fight
    self._during_fight()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\decisive_battle.py", line 697, in _during_fight
    plan.run()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\common.py", line 372, in run
    return self.fight()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\common.py", line 291, in fight
    ret = self._make_decision()
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\battle.py", line 115, in _make_decision
    state = self.update_state() if 'skip_update' not in kwargs else self.info.state
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\common.py", line 464, in update_state
    self._make_decision(skip_update=True)
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\battle.py", line 122, in _make_decision
    action, fight_stage = self.node.make_decision(
  File "C:\Users\winger\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\autowsgr\fight\common.py", line 738, in make_decision
    raise BaseException
BaseException
```

**Comment by huan-yp** [comment]
无法复现，请提供更多信息：

1. 除了决战外的日常战斗能否出现这种情况？

**Comment by Winger-Wang** [comment]
> 无法复现，请提供更多信息：
> 
> 1. 除了决战外的日常战斗能否出现这种情况？

除了决战外，可以在战役、演习时发现这种情况。
我最近注意到，在卡住的情况下手动点击屏幕，就可以不会卡死。我过段时间可能自己研究下改变模拟点击位置会不会有影响。
