### ISSUE TITLE
第一次使用报错

### ISSUE THREAD

**Issue by SNSU16** [OpenWSGR/AutoWSGR#131]
03:16:28 autowsgr  INFO  | 启动成功, 当前位置: main_page
Traceback (most recent call last):
  File "E:\AutoWSGR-main\examples\auto_daily.py", line 8, in <module>
    operation = DailyOperation(timer)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\scripts\daily_api.py", line 16, in __init__
    self.timer = start_script(setting_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\scripts\main.py", line 75, in start_script
    config, logger = initialize_logger_and_config(settings_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\scripts\main.py", line 29, in initialize_logger_and_config
    user_settings = yaml_to_dict(settings_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autowsgr\utils\io.py", line 31, in yaml_to_dict
    with open(yaml_file, "r", encoding="utf-8") as f:
TypeError: expected str, bytes or os.PathLike object, not Timer
/
/

**Comment by veadex** [comment]
autowsgr请更新到最新版1.3.2，如果无法更新请检查自己的Python版本是否是3.10
